grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana-a.local
    tls:
      - secretName: grafana-a-tls
        hosts:
          - grafana-a.local